export const imageData = {
  Серый: 'images/colors/1.webp',
  Серый1: 'images/colors/2.webp',
  Серый2: 'images/colors/4.webp',
  Серый3: 'images/colors/5.webp',
  Серый4: 'images/colors/6.webp',
  Серый5: 'images/colors/8.webp',
  Коричневый: 'images/colors/9.webp',
  Коричневый1: 'images/colors/10.webp',
  Коричневый2: 'images/colors/11.webp',
  Коричневый3: 'images/colors/12.webp',
  Коричневый4: 'images/colors/13.webp',
  Зеленый: 'images/colors/14.webp',
  Зеленый1: 'images/colors/15.webp',
  Зеленый2: 'images/colors/16.webp',
  Зеленый3: 'images/colors/17.webp',
};
